Add cookieDomain option
auth0/auth0.js pull request #1304
Opened 2023-05-10 15:46 UTC by telmaantunes

### Changes

Adds an optional cookieDomain setting to the client options that allows the cookie domain to be explicitly set.

This is intended to allow a cookie to work across subdomains by setting it to top-level domain (eg: .example.com).

### References

Solution to this `[issue](https://github.com/auth0/auth0.js/issues/1303)`.
 
### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.

- [x] This change adds unit test coverage
- [ ] This change adds integration test coverage

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All tests and linters described in the [Develop section](https://github.com/auth0/auth0.js#develop) run without errors

2023-05-22 10:31 UTC, frederikprijck requested changes
Thanks for this PR, the changes look great, but we are missing passing the domain when caling `remove`, can you add that as well as add a test for that?

2023-05-23 17:56 UTC, telmaantunes commented
@frederikprijck You're right, sorry about that 🤦‍♀️ Done!

2023-05-24 07:16 UTC, frederikprijck approved these changes

2023-05-24 07:16 UTC, frederikprijck commented
Thanks for the PR 🚀

2023-05-24 07:22 UTC, merged